### ISSUE TITLE
mvn clean install sakai:deploy is failed

### ISSUE THREAD

**Issue by NThirumalReddy** [kaltura/sakai-extension#109]
Hi,
i'm using sakai 11.2 
while integrating kaltura with sakai. i'm getting build errors.
when i run mvn clean install cmd from root folder of sakai-extension-master it is giving following build failure message.

> [INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[WARNING] 'parent.relativePath' of POM org.sakaiproject.kaltura:kaltura:[unknown
-version] (E:\Sakai\Sakai11WorkSpace\sakai-11.2\sakai-extension-master\pom.xml)
points at org.sakaiproject:base instead of org.sakaiproject:master, please verif
y your project structure @ org.sakaiproject.kaltura:kaltura:[unknown-version], E
:\Sakai\Sakai11WorkSpace\sakai-11.2\sakai-extension-master\pom.xml, line 5, colu
mn 11
[WARNING] 'parent.relativePath' of POM org.sakaiproject.kaltura:kaltura:[unknown
-version] (E:\Sakai\Sakai11WorkSpace\sakai-11.2\sakai-extension-master\pom.xml)
points at org.sakaiproject:base instead of org.sakaiproject:master, please verif
y your project structure @ org.sakaiproject.kaltura:kaltura:[unknown-version], E
:\Sakai\Sakai11WorkSpace\sakai-11.2\sakai-extension-master\pom.xml, line 5, colu
mn 11
[WARNING] 'parent.relativePath' of POM org.sakaiproject.kaltura:kaltura:[unknown
-version] (E:\Sakai\Sakai11WorkSpace\sakai-11.2\sakai-extension-master\pom.xml)
points at org.sakaiproject:base instead of org.sakaiproject:master, please verif
y your project structure @ org.sakaiproject.kaltura:kaltura:[unknown-version], E
:\Sakai\Sakai11WorkSpace\sakai-11.2\sakai-extension-master\pom.xml, line 5, colu
mn 11
[ERROR] 'dependencies.dependency.version' for org.sakaiproject.genericdao:generi
c-dao:jar must be a valid version but is '${sakai.genericdao.version}'. @ org.sa
kaiproject.kaltura:kaltura-api:[unknown-version], E:\Sakai\Sakai11WorkSpace\saka
i-11.2\sakai-extension-master\api\pom.xml, line 27, column 16
[WARNING] 'parent.relativePath' of POM org.sakaiproject.kaltura:kaltura:[unknown
-version] (E:\Sakai\Sakai11WorkSpace\sakai-11.2\sakai-extension-master\pom.xml)
points at org.sakaiproject:base instead of org.sakaiproject:master, please verif
y your project structure @ org.sakaiproject.kaltura:kaltura:[unknown-version], E
:\Sakai\Sakai11WorkSpace\sakai-11.2\sakai-extension-master\pom.xml, line 5, colu
mn 11
[WARNING] 'parent.relativePath' of POM org.sakaiproject.kaltura:kaltura:[unknown
-version] (E:\Sakai\Sakai11WorkSpace\sakai-11.2\sakai-extension-master\pom.xml)
points at org.sakaiproject:base instead of org.sakaiproject:master, please verif
y your project structure @ org.sakaiproject.kaltura:kaltura:[unknown-version], E
:\Sakai\Sakai11WorkSpace\sakai-11.2\sakai-extension-master\pom.xml, line 5, colu
mn 11
[WARNING] 'parent.relativePath' of POM org.sakaiproject.kaltura:kaltura:[unknown
-version] (E:\Sakai\Sakai11WorkSpace\sakai-11.2\sakai-extension-master\pom.xml)
points at org.sakaiproject:base instead of org.sakaiproject:master, please verif
y your project structure @ org.sakaiproject.kaltura:kaltura:[unknown-version], E
:\Sakai\Sakai11WorkSpace\sakai-11.2\sakai-extension-master\pom.xml, line 5, colu
mn 11
[WARNING] 'parent.relativePath' of POM org.sakaiproject.kaltura:kaltura:[unknown
-version] (E:\Sakai\Sakai11WorkSpace\sakai-11.2\sakai-extension-master\pom.xml)
points at org.sakaiproject:base instead of org.sakaiproject:master, please verif
y your project structure @ org.sakaiproject.kaltura:kaltura:[unknown-version], E
:\Sakai\Sakai11WorkSpace\sakai-11.2\sakai-extension-master\pom.xml, line 5, colu
mn 11
[WARNING] 'parent.relativePath' of POM org.sakaiproject.kaltura:kaltura:[unknown
-version] (E:\Sakai\Sakai11WorkSpace\sakai-11.2\sakai-extension-master\pom.xml)
points at org.sakaiproject:base instead of org.sakaiproject:master, please verif
y your project structure @ org.sakaiproject.kaltura:kaltura:[unknown-version], E
:\Sakai\Sakai11WorkSpace\sakai-11.2\sakai-extension-master\pom.xml, line 5, colu
mn 11
[WARNING] 'parent.relativePath' of POM org.sakaiproject.kaltura:kaltura:[unknown
-version] (E:\Sakai\Sakai11WorkSpace\sakai-11.2\sakai-extension-master\pom.xml)
points at org.sakaiproject:base instead of org.sakaiproject:master, please verif
y your project structure @ org.sakaiproject.kaltura:kaltura:[unknown-version], E
:\Sakai\Sakai11WorkSpace\sakai-11.2\sakai-extension-master\pom.xml, line 5, colu
mn 11
 @
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project org.sakaiproject.kaltura:kaltura-api:11-SNAPSHOT (E:\Sakai
\Sakai11WorkSpace\sakai-11.2\sakai-extension-master\api\pom.xml) has 1 error
[ERROR]     'dependencies.dependency.version' for org.sakaiproject.genericdao:ge
neric-dao:jar must be a valid version but is '${sakai.genericdao.version}'. @ or
g.sakaiproject.kaltura:kaltura-api:[unknown-version], E:\Sakai\Sakai11WorkSpace\
sakai-11.2\sakai-extension-master\api\pom.xml, line 27, column 16
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildin
gException

Thanks
Thirumal

**Comment by kaltura-hooks** [comment]
Hi @NThirumalReddy,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa \"kaltura*\"
```	
	For deb based systems:
```	
	# dpkg -l \"kaltura-*\"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by gonenradai** [comment]
Hi @NThirumalReddy 
Did you follow the installation instructions here - https://knowledge.kaltura.com/kaltura-video-tool-sakai-installation-and-upgrade-guide-version-40?

In general, know that you should take the version from a tag and not use the master branch.
For Sakai 11.2 you should use the version 5.0.1 - https://github.com/kaltura/sakai-extension/releases/tag/v5.0.1 (so you will need checkout this tag in your local working copy of the repo).

**Comment by NThirumalReddy** [comment]
Hi All,
Installation issue was resolved.
Later i created a site with Media Gallery Tool
but while accessing in site i'm getting an issue.
i.e,

> org.sakaiproject.portal.api.PortalHandlerException: org.sakaiproject.tool.api.ToolException: org.springframework.web.util.NestedServletException: Request processing failed; nested exception is java.lang.NullPointerException
    at org.sakaiproject.portal.charon.SkinnableCharonPortal.doGet(SkinnableCharonPortal.java:849)
caused by: org.sakaiproject.tool.api.ToolException: org.springframework.web.util.NestedServletException: Request processing failed; nested exception is java.lang.NullPointerException
    at org.sakaiproject.portal.charon.SkinnableCharonPortal.forwardTool(SkinnableCharonPortal.java:1475)
caused by: org.springframework.web.util.NestedServletException: Request processing failed; nested exception is java.lang.NullPointerException
    at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:858)
caused by: java.lang.NullPointerException
    at net.oauth.signature.OAuthSignatureMethod.normalizeUrl(OAuthSignatureMethod.java:177)
    at net.oauth.signature.OAuthSignatureMethod.getBaseString(OAuthSignatureMethod.java:171)
    at net.oauth.signature.OAuthSignatureMethod.getSignature(OAuthSignatureMethod.java:97)
    at net.oauth.signature.OAuthSignatureMethod.sign(OAuthSignatureMethod.java:49)
    at net.oauth.OAuthMessage.sign(OAuthMessage.java:299)
    at net.oauth.OAuthMessage.addRequiredParameters(OAuthMessage.java:289)
    at org.tsugi.basiclti.BasicLTIUtil.signProperties(BasicLTIUtil.java:334)
    at org.tsugi.basiclti.BasicLTIUtil.signProperties(BasicLTIUtil.java:268)
    at org.sakaiproject.kaltura.services.KalturaLTIService.launchLTIRequest(KalturaLTIService.java:145)
    at org.sakaiproject.kaltura.services.KalturaLTIService.launchLTIRequest(KalturaLTIService.java:85)
    at org.sakaiproject.kaltura.controllers.MediaGalleryController.handleRequestInternal(MediaGalleryController.java:31)
    at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:147)
    at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:50)
    at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:961)
    at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:895)
    at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:967)
    at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:858)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:622)
    at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:843)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:101)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
    at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
    at org.sakaiproject.util.RequestFilter.doFilter(RequestFilter.java:411)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
    at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:720)
    at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:466)
    at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:391)
    at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:318)
    at uk.ac.cam.caret.sakai.WebappToolServlet.service(WebappToolServlet.java:56)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
    at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:121)
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
    at org.sakaiproject.util.RequestFilter.doFilter(RequestFilter.java:411)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
    at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:720)
    at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:466)
    at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:358)
    at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:318)
    at org.sakaiproject.tool.impl.ActiveToolComponent$MyActiveTool.forward(ActiveToolComponent.java:513)
    at org.sakaiproject.portal.charon.SkinnableCharonPortal.forwardTool(SkinnableCharonPortal.java:1475)
    at org.sakaiproject.portal.charon.handlers.ToolHandler.doTool(ToolHandler.java:204)
    at org.sakaiproject.portal.charon.handlers.ToolHandler.doGet(ToolHandler.java:100)
    at org.sakaiproject.portal.charon.SkinnableCharonPortal.doGet(SkinnableCharonPortal.java:849)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:622)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
    at org.sakaiproject.util.RequestFilter.doFilter(RequestFilter.java:460)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
    at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
    at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:522)
    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1095)
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:672)
    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1500)
    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1456)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(null:-1)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(null:-1)
    at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
    at java.lang.Thread.run(null:-1)
user: admin
usage-session: ac52cefb-373b-4ad4-aaf1-802a9712e3b9
time: Apr 25, 2017 18:52:25


I modified sakai extension root folder of sakai.properties file with below properties..

kaltura.launch.key= Partner Id
kaltura.launch.secret= Admin Secret Key

kaltura.host= http://www.kaltura.com

kaltura.media.static.playersize=400x285
kaltura.media.static.playerskin=2990794

kaltura.ckeditor.url=###CHANGEME###
kaltura.ckeditor.callback.url=###CHANGEME###/media-gallery-tool/ckeditorcallback.htm


I dont know what i need to place at ckeditor.url and ckeditor.callback.url
And is kaltura.host value is right..?

Thanks,
Thirumal

**Comment by gonenradai** [comment]
Hi @NThirumalReddy 

I think the NullPointerException is because you edited the sakai.properties file inside the extension.
You should be copying the kaltura related configurations either to sakai.properties or local.properties under the sakai folder inside tomcat.
The sakai.properties in this repository is just an example to show the required configurations.

The kaltura.host configuration is wrong.
It should be your KAF URL (usually in the form of {partnerID}.kaf.kaltura.com.
If you don't have such or don't know, contact Kaltura Customer Care for assistance (they will need your partner ID).

According to the code, there is no use anymore in kaltura.ckeditor.url or kaltura.ckeditor.callback.url.

**Comment by NThirumalReddy** [comment]
Hi @gonenradai 

Thanks for u'r replay

I followed your suggestions and changed kaltura.host value
but at the time of accessing Media Gallery Tool in sakai it is redirecting to https://partnerID.kaf.kaltura.com/hosted/index/course-gallery url 
but that page  isn’t working.
what might be the problem your expecting.?
mean while i'll contact with Kaltura Customer Care

Regards,
Thirumal.

**Comment by gonenradai** [comment]
if your Sakai is running on HTTP, you should change the KAF configuration so it is HTTP as well.
if they are mixed (Sakai is HTTP, but KAF is configured to force HTTPS) the extra redirect will probably lose the LTI data which will result in an "access denied" message.

To configure your KAF to be HTTP only, go to the KAF configuration (https://partnerID.kaf.kaltura.com/admin/config) and switch to the "auth" tab.
In that configuration page look for the sslSettings field and switch it from "All Site" to "None", and save the configuration.

**Comment by NThirumalReddy** [comment]
Hi @gonenradai 

https://partnerId.kaf.kaltura.com/admin/config
url also not working..

Regards,
Thirumal.

**Comment by gonenradai** [comment]
if it wasn't clear, you should change the "partnerId" in the URL to your Kaltura partner ID (it is a number).
For example, one partner would have
1234.kaf.kaltura.com
and another would have
982736.kaf.kaltura.com

**Comment by NThirumalReddy** [comment]
Yeah i know that..
I took partner Id from http://kmc.kaltura.com/index.php/kmc/kmc4#account|integration
Is it right.?

**Comment by gonenradai** [comment]
correct, could be that you do not have a KAF instance for Sakai.
Please continue with Kaltura Customer Care (as we really need your partner ID at this point) to help resolve.
